#!/usr/bin/env bash

# see https://mths.be/macos

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

defaults write com.apple.finder ShowStatusBar -bool true

# show path bar: Finder
defaults write com.apple.finder ShowPathbar -bool true

# Speed up Mission Control animations
defaults write com.apple.dock expose-animation-duration -float 0.1

defaults write com.apple.dock autohide -bool true
